name: inpainting
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8                                     
  - ca-certificates=2021.1.19                                     
  - certifi=2020.12.5                                     
  - cudatoolkit=10.2.89                                     
  - ffmpeg=4.3                                     
  - freetype=2.10.4                                                                                                  
  - intel-openmp=2020.2=254
  - jpeg=9b                                     
  - lame=3.100                                     
  - lcms2=2.11                                                                     
  - libffi=3.3                                                                      
  - libiconv=1.15                                     
  - libpng=1.6.37                                                                      
  - libtiff=4.1.0                                     
  - libuv=1.40.0                                     
  - lz4-c=1.9.3                                     
  - mkl=2020.2=256
  - mkl-service=2.3.0                                     
  - mkl_fft=1.3.0                                    
  - mkl_random=1.1.1                                                                                                        
  - ninja=1.10.2                                     
  - numpy=1.19.2                                     
  - numpy-base=1.19.2                                    
  - olefile=0.46=py_0                                  
  - openssl=1.1.1k                                     
  - pillow=8.1.2                                    
  - pip=21.0.1                                     
  - python=3.8.8                                     
  - pytorch=1.8.1                                                                      
  - setuptools=52.0.0                                     
  - six=1.15.0                                     
  - sqlite=3.35.3                                     
  - tk=8.6.10                                     
  - torchaudio=0.8.1=py38
  - torchvision=0.9.1=py38_cu102
  - typing_extensions=3.7.4.3                                     
  - wheel=0.36.2                                     
  - xz=5.2.5                                     
  - zlib=1.2.11                                     
  - zstd=1.4.9  
                                     
  - pip:
    - absl-py==0.12.0
    - attrdict==2.0.1
    - cachetools==4.2.1
    - chardet==4.0.0
    - cycler==0.10.0
    - decorator==5.0.3
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.4
    - grpcio==1.36.1
    - idna==2.10
    - imageio==2.9.0
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.4.1
    - networkx==2.5
    - oauthlib==3.1.0
    - opencv-python==4.5.1.48
    - protobuf==3.15.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pywavelets==1.1.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-image==0.18.1
    - scipy==1.6.2
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tifffile==2021.3.31
    - tqdm==4.59.0
    - urllib3==1.26.4
    - werkzeug==1.0.1 
